site_name: Acta Cryologica
nav:
  - Home: index.md
  - Experiments:
    - Comparisons: experiments/comparisons.md # works for a page
    - New flavors: experiments/new-flavors/index.md # Need index.md for nesting past this level
  - Base Recipes: 
    - Custard Base: base-recipes/custard-base.md
  - Plots: plots/plots.md
theme:
  name: simple-blog
  features:
    - search.suggest
